# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

chicken_parm = Dish.create(name: 'Chicken Parmesan', photo_url: 'https://static01.nyt.com/images/2015/02/04/dining/04PARM2/04PARM2-master675.jpg', ingredients: ['chicken', 'flour', 'egg', 'panko', 'olive oil', 'tomato sauce', 'parmesan', 'mozzarella'], tags: ['comfort food', 'family'], category: ['Italian'], price: 6, portion: '1 plate', quantity: 4, user_id: 1, description: "A classic Italian-American Parmesan — a casserole of fried, breaded meat or eggplant covered with tomato sauce and molten cheese — is all about balance. You need a bracing a tomato sauce to cut out the fried richness, while a milky, mild mozzarella rounds out the Parmesan’s tang. Baked until brown-edged and bubbling, it’s classic comfort food — hearty, gooey and satisfying. Although chicken or veal cutlets are the standard, boneless, skinless chicken thighs make a more flavorful alternative. Pork or turkey cutlets work nicely here, too.")
fish_tacos = Dish.create(name: 'Fish Tacos', photo_url: 'https://static01.nyt.com/images/2014/05/12/dining/Fish-Tacos/Fish-Tacos-videoSixteenByNine495.jpg', ingredients: ['tomato', 'red onion', 'garlic', 'cilantro', 'jalapeno', 'lime', 'chipotle pepper', 'flour', 'chili powder', 'milk', 'peanut oil', 'flounder', 'corn tortilla', 'green cabbage'], tags: ['spicy', 'party'], category: ['Mexican'], price: 2, portion: '1 taco', quantity: 8, user_id: 1, description: "Fish tacos, that great meal of the Baja Peninsula, and a taste of summer. They are simple to make, no more complicated in fact than a hamburger or a mess of pancakes, and they are considerably more flavorful. Fried in strips and served onboard warm corn tortillas with a simple salsa, a pinch of fresh cabbage, plenty of lime and a cream sauce you might want to punch up with some chopped chipotle, these fish tacos can turn a cold night into bluebird summer, transporting you from chill into deep humidity and bliss.")
shrimp = Dish.create(name: 'Hot Honey Shrimp', photo_url: 'https://static01.nyt.com/images/2016/06/16/multimedia/clark-hot-honey-shrimp/clark-hot-honey-shrimp-mediumThreeByTwo252.jpg', ingredients: ['honey', 'lime', 'cayenne powder', 'ginger', 'garlic', 'shrimp', 'butter', 'jalapeno', 'chives'], tags: ['easy', 'spicy', 'party'], category: ['BBQ'], price: 3, portion: '5 shrimp', quantity: 6, user_id: 1, description: "Chile powder adds sting, honey lends sweetness, and butter gives a creamy richness to these succulent roasted shrimp. Even better, the dish comes together in minutes, making it an ideal after-work meal or extremely speedy appetizer. The shrimp are also excellent tucked into a baguette for a shrimp sandwich. If you happen to have a jar of hot honey (chile-spiced honey), you can use that instead of combining the honey and cayenne. Just be sure to use a light hand with the lime juice at the very end; hot honey also contains vinegar, so taste as you go. If you'd like to double the recipe, you can. Just use two baking pans so as not to crowd the shrimp.")
brownies = Dish.create(name: 'Salted Caramel Brownies', photo_url: 'https://static01.nyt.com/images/2016/06/07/dining/salted-caramel-brownie-2/salted-caramel-brownie-2-mediumThreeByTwo252.jpg', ingredients: ['sugar', 'corn syrup', 'heavy cream', 'sour cream', 'butter', 'flour', 'cocoa powder', 'dark chocolate', 'brown sugar', 'egg', 'vanilla extract'], tags: ['sweet', 'rich'], category: ['Dessert'], price: 2, portion: '1 brownie', quantity: 20, user_id: 1, description: "The salted caramel brownie is an ingenious combination of blond, bittersweet caramel and dark, bittersweet chocolate. Matt Lewis and Renato Poliafito of New York's Baked bakeries are not the first to note the affinity of caramel and chocolate, but by emphasizing the bitter, sweet and salty notes in both, they’ve made that rare thing — a perfectly balanced bite. The bittersweetness of the caramel can be easily adjusted by cooking it less (for a milder, Kraft-like taste) or more (edgier, stronger).")
summer_pasta = Dish.create(name: 'Summer Pasta With Zucchini, Ricotta and Basil', photo_url: 'https://static01.nyt.com/images/2015/06/17/dining/17KITCH1/17KITCH1-master675.jpg', ingredients: ['EVOO', 'onion', 'garlic', 'zucchini', 'basil', 'ziti', 'ricotta', 'lemon', 'parmesan'], tags: ['summer'], category: ['Italian'], price: 6, portion: '1 plate', quantity: 4, user_id: 1, description: "A summer pasta should be simple and fresh, ideally made with vegetables straight from the garden or market. Look for the best artisanal ricotta; top-quality ingredients make all the difference here.")
enchiladas = Dish.create(name: 'Enchiladas Con Carne', photo_url: 'https://static01.nyt.com/images/2016/06/01/dining/01ENCHALADAS1-WEB/01ENCHALADAS1-WEB-master675.jpg', ingredients: ['flour', 'canola oil', 'ground beef', 'white onion', 'jalapeno', 'tomato', 'chili powder', 'cumin', 'oregano', 'chicken stock', 'corn tortilla', 'cheddar cheese'], tags: ['comfort food', 'family'], category: ['Mexican'], price: 4, portion: '2 enchiladas', quantity: 7, user_id: 1, description: "There are a few cool tricks to this recipe, one of which I picked up from an old issue of Bon Appétit, one I learned from Robb Walsh, the great Tex-Mex scholar and restaurateur who runs El Real Tex-Mex in Houston, and a final one I learned by happenstance. First, for the thickening agent in the chile sauce, toast raw all-purpose flour in a pan until it is nutty and golden brown, then reserve it to stir in with the browned beef later in the recipe. Second, if you like truly melty cheese in the classic Tex-Mex tradition, use a mixture of American cheese, like Velveeta, with the Cheddar you use inside and on top of the finished enchiladas. Finally, if you’re fearful that a casserole of cheese, chili and fried tortillas may be a little rich for dinner, serve it with a bowl of tomatillo pineapple salsa on the side. The acidity provides a nice balance. (Note also that as with all recipes, but particularly this one, some planning and practice can get the preparation down to 60 minutes.)")
carrot_soup = Dish.create(name: 'Spiced Carrot Soup With Lime', photo_url: 'https://static01.nyt.com/images/2016/06/08/dining/08KITCHEN1-WEB/08KITCHEN1-WEB-master675.jpg', ingredients: ['vegetable oil', 'onion', 'garlic', 'ginger', 'turmeric', 'coriander', 'cayenne pepper', 'carrot', 'daikon radish', 'mustard seeds', 'cumin seeds', 'flounder', 'serrano pepper', 'lime'], tags: ['spicy'], category: ['Indian'], price: 3, portion: '1 bowl', quantity: 9, user_id: 1, description: "Here is the antidote to cloying, overly sweet, one-dimensional, too-thick carrot soup: fresh carrots, bright spices and a squeeze of lime. The final sizzling of cumin and mustard seeds in coconut oil — the technique is known as tarka in Indian cuisine — adds an extra blast of flavor. Look for young carrots, long and slender, which are far fresher and tastier than the fat ones that come in jumbo bags. In warm weather, you can serve the soup chilled if you'd like.")
lobster_linquine = Dish.create(name: 'Linguine With Lobster and Avocado', photo_url: 'https://static01.nyt.com/images/2016/06/08/dining/08PAIRING-WEB/08PAIRING-master675.jpg', ingredients: ['grape tomato', 'onion', 'lemon', 'avocado', 'linguine', 'jalapeno', 'lobster', 'scallion', 'cilanto'], tags: ['summer', 'lobster'], category: ['Spanish', 'Italian'], price: 8, portion: '1 plate', quantity: 3, user_id: 1, description: "The summer season was beginning, whetting the appetite for a copious seafood salad or a tangy ceviche. But instead, I tore a page from ceviche’s playbook and assembled a pasta dish with the avocado, tomato, jalapeño, scallion, cilantro and citrus juice, along with lobster, to mingle with pasta. The result was brightly fresh-tasting, a warm-weather charmer with a touch of spice. Even during the brief cooking, some of the avocado will melt into the mixture, suavely coating the strands of linguine. But be sure that some of the avocado is still intact. The dish is satisfying as the main event yet light enough to serve as a first course followed by chicken or sausages hot off the grill.")
spaghetti = Dish.create(name: 'Spaghetti With Fresh Tomato and Basil Sauce', photo_url: 'https://static01.nyt.com/images/2015/07/27/dining/27SPAGHETTI/27SPAGHETTI-master675.jpg', ingredients: ['plum tomato', 'olive oil', 'red pepper flakes', 'spaghetti', 'EVOO', 'butter', 'basil', 'parmesan'], tags: ['comfort food', 'family'], category: ['Italian'], price: 6, portion: '1 plate', quantity: 13, user_id: 1, description: "This recipe came to The Times in 2003 from the chef Scott Conant, who was then cooking at his restaurant L'Impero in Manhattan. It is simple, classic Italian fare that makes the most of summer's tomatoes, but you can also make it with hothouse offerings and it will be delicious.")
crepes = Dish.create(name: 'Crêpes Suzette', photo_url: 'https://static01.nyt.com/images/2016/05/28/dining/28COOKING-CREPES-SUZETTE1/28COOKING-CREPES-SUZETTE1-master675.jpg', ingredients: ['orange juice', 'orange', 'butter', 'sugar', 'Grand Marnier', 'flour', 'egg', 'milk'], tags: ['sweet'], category: ['French', 'Dessert'], price: 2, portion: '1 crepe', quantity: 11, user_id: 1, description: "This is just one of those desserts that seem, on the page as on the plate, to be labor-intensive and tricky, but in fact are as simple to make as they are gratifying to eat. For one thing, you can make the crepes in advance; they could sit, piled between torn-off sheets of baking parchment and well wrapped in the refrigerator, for a good three days without coming to any harm. But I must admit to taking, more than once, an even quicker route: using good store-bought crepes. Once they're immersed in the sweet orangey syrup, they will not betray their prefabricated origins.")

# harry = User.create(name: 'Harry Potter', zip_code: 20001, photo_url: 'http://images1.wikia.nocookie.net/__cb20111110202524/harrypotter/images/thumb/d/d4/Dhharryroomhighreso.jpg/250px-Dhharryroomhighreso.jpg', ethnicities: ['Italian', 'American', 'Mexican'])
# hermione = User.create(name: 'Hermione Granger', zip_code: 90291, photo_url: 'http://images2.wikia.nocookie.net/__cb20120512155742/harrypotter/images/thumb/9/95/DeathlyPromo_Hermione.PNG/250px-DeathlyPromo_Hermione.PNG', ethnicities: ['Chinese', 'American', 'British'])
# ron = User.create(name: 'Ron Weasley', zip_code: 20009, photo_url: 'http://images4.wikia.nocookie.net/__cb20090712085217/harrypotter/images/9/99/Ron_DH.PNG', ethnicities: ['Thai', 'Mexican'])
# draco = User.create(name: 'Draco Malfoy', zip_code: 53703, photo_url: 'http://images1.wikia.nocookie.net/__cb20100925140918/harrypotter/images/thumb/2/21/Dracodh.jpg/250px-Dracodh.jpg', ethnicities: ['Italian', 'American', 'Mexican'])
# luna = User.create(name: 'Luna Lovegood', zip_code: 53711, photo_url: 'http://images1.wikia.nocookie.net/__cb20101113121321/harrypotter/images/thumb/4/49/Luna_profile.jpg/250px-Luna_profile.jpg', ethnicities: ['Italian', 'American', 'Mexican'])
# cho = User.create(name: 'Cho Chang', zip_code: 90007, photo_url: 'http://images3.wikia.nocookie.net/__cb20081103140303/harrypotter/images/thumb/c/c1/Cho_Chang_Profile.JPG/250px-Cho_Chang_Profile.JPG', ethnicities: ['Italian', 'American', 'Mexican'])
