# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

chicken_parm = Dish.create(name: 'Chicken Parmesan', photo_url: 'https://static01.nyt.com/images/2015/02/04/dining/04PARM2/04PARM2-master675.jpg', ingredients: ['chicken', 'flour', 'egg', 'panko', 'olive oil', 'tomato sauce', 'parmesan', 'mozzarella'], tags: ['comfort food', 'family'], category: 'Italian', price: 6, portion: '1 plate', quantity: 4)
fish_tacos = Dish.create(name: 'Fish Tacos', photo_url: 'https://static01.nyt.com/images/2014/05/12/dining/Fish-Tacos/Fish-Tacos-videoSixteenByNine495.jpg', ingredients: ['tomato', 'red onion', 'garlic', 'cilantro', 'jalapeno', 'lime', 'chipotle pepper', 'flour', 'chili powder', 'milk', 'peanut oil', 'flounder', 'corn tortilla', 'green cabbage'], tags: ['spicy', 'party'], category: ['Mexican'], price: 2, portion: '1 taco', quantity: 8)
shrimp = Dish.create(name: 'Hot Honey Shrimp', photo_url: 'https://static01.nyt.com/images/2016/06/16/multimedia/clark-hot-honey-shrimp/clark-hot-honey-shrimp-mediumThreeByTwo252.jpg', ingredients: ['honey', 'lime', 'cayenne powder', 'ginger', 'garlic', 'shrimp', 'butter', 'jalapeno', 'chives'], tags: ['easy', 'spicy', 'party'], category: ['BBQ'], price: 3, portion: '5 shrimp', quantity: 6)
brownies = Dish.create(name: 'Salted Caramel Brownies', photo_url: 'https://static01.nyt.com/images/2016/06/07/dining/salted-caramel-brownie-2/salted-caramel-brownie-2-mediumThreeByTwo252.jpg', ingredients: ['sugar', 'corn syrup', 'heavy cream', 'sour cream', 'butter', 'flour', 'cocoa powder', 'dark chocolate', 'brown sugar', 'egg', 'vanilla extract'], tags: ['sweet', 'rich'], category: ['Dessert'], price: 2, portion: '1 brownie', quantity: 20)
summer_pasta = Dish.create(name: 'Summer Pasta With Zucchini, Ricotta and Basil', photo_url: 'https://static01.nyt.com/images/2015/06/17/dining/17KITCH1/17KITCH1-master675.jpg', ingredients: ['EVOO', 'onion', 'garlic', 'zucchini', 'basil', 'ziti', 'ricotta', 'lemon', 'parmesan'], tags: ['summer'], category: ['Italian'], price: 6, portion: '1 plate', quantity: 4)
enchiladas = Dish.create(name: 'Enchiladas Con Carne', photo_url: 'https://static01.nyt.com/images/2016/06/01/dining/01ENCHALADAS1-WEB/01ENCHALADAS1-WEB-master675.jpg', ingredients: ['flour', 'canola oil', 'ground beef', 'white onion', 'jalapeno', 'tomato', 'chili powder', 'cumin', 'oregano', 'chicken stock', 'corn tortilla', 'cheddar cheese'], tags: ['comfort food', 'family'], category: ['Mexican'], price: 4, portion: '2 enchiladas', quantity: 7)
carrot_soup = Dish.create(name: 'Spiced Carrot Soup With Lime', photo_url: 'https://static01.nyt.com/images/2016/06/08/dining/08KITCHEN1-WEB/08KITCHEN1-WEB-master675.jpg', ingredients: ['vegetable oil', 'onion', 'garlic', 'ginger', 'turmeric', 'coriander', 'cayenne pepper', 'carrot', 'daikon radish', 'mustard seeds', 'cumin seeds', 'flounder', 'serrano pepper', 'lime'], tags: ['spicy'], category: ['Indian'], price: 3, portion: '1 bowl', quantity: 9)
lobster_linquine = Dish.create(name: 'Linguine With Lobster and Avocado', photo_url: 'https://static01.nyt.com/images/2016/06/08/dining/08PAIRING-WEB/08PAIRING-master675.jpg', ingredients: ['grape tomato', 'onion', 'lemon', 'avocado', 'linguine', 'jalapeno', 'lobster', 'scallion', 'cilanto'], tags: ['summer', 'lobster'], category: ['Spanish', 'Italian'], price: 8, portion: '1 plate', quantity: 3)
spaghetti = Dish.create(name: 'Spaghetti With Fresh Tomato and Basil Sauce', photo_url: 'https://static01.nyt.com/images/2015/07/27/dining/27SPAGHETTI/27SPAGHETTI-master675.jpg', ingredients: ['plum tomato', 'olive oil', 'red pepper flakes', 'spaghetti', 'EVOO', 'butter', 'basil', 'parmesan'], tags: ['comfort food', 'family'], category: ['Italian'], price: 6, portion: '1 plate', quantity: 13)
crepes = Dish.create(name: 'Crêpes Suzette', photo_url: 'https://static01.nyt.com/images/2016/05/28/dining/28COOKING-CREPES-SUZETTE1/28COOKING-CREPES-SUZETTE1-master675.jpg', ingredients: ['orange juice', 'orange', 'butter', 'sugar', 'Grand Marnier', 'flour', 'egg', 'milk'], tags: ['sweet'], category: ['French', 'Dessert'], price: 2, portion: '1 crepe', quantity: 11)

harry = User.create(name: 'Harry Potter', zip_code: 20001, photo_url: 'http://images1.wikia.nocookie.net/__cb20111110202524/harrypotter/images/thumb/d/d4/Dhharryroomhighreso.jpg/250px-Dhharryroomhighreso.jpg', ethnicities: ['Italian', 'American', 'Mexican'])
hermione = User.create(name: 'Hermione Granger', zip_code: 90291, photo_url: 'http://images2.wikia.nocookie.net/__cb20120512155742/harrypotter/images/thumb/9/95/DeathlyPromo_Hermione.PNG/250px-DeathlyPromo_Hermione.PNG', ethnicities: ['Chinese', 'American', 'British'])
ron = User.create(name: 'Ron Weasley', zip_code: 20009, photo_url: 'http://images4.wikia.nocookie.net/__cb20090712085217/harrypotter/images/9/99/Ron_DH.PNG', ethnicities: ['Thai', 'Mexican'])
draco = User.create(name: 'Draco Malfoy', zip_code: 53703, photo_url: 'http://images1.wikia.nocookie.net/__cb20100925140918/harrypotter/images/thumb/2/21/Dracodh.jpg/250px-Dracodh.jpg', ethnicities: ['Italian', 'American', 'Mexican'])
luna = User.create(name: 'Luna Lovegood', zip_code: 53711, photo_url: 'http://images1.wikia.nocookie.net/__cb20101113121321/harrypotter/images/thumb/4/49/Luna_profile.jpg/250px-Luna_profile.jpg', ethnicities: ['Italian', 'American', 'Mexican'])
cho = User.create(name: 'Cho Chang', zip_code: 90007, photo_url: 'http://images3.wikia.nocookie.net/__cb20081103140303/harrypotter/images/thumb/c/c1/Cho_Chang_Profile.JPG/250px-Cho_Chang_Profile.JPG', ethnicities: ['Italian', 'American', 'Mexican'])
